### PR TITLE
Loading libhdf5 dynamically from bitshuffle.h5

### PR DESCRIPTION
**Pull request by t20100**
This PR proposes to adapt the dynamic loading of libhdf5 used in https://github.com/silx-kit/hdf5plugin to `bitshuffle.h5`.
This allows to build `bitshuffle` without linking to a specific version of the HDF5 library.
This would enable the creation of wheels for `bitshuffle`.

This PR does not modify the plugin part of bitshuffle, only `bitshuffle.h5`.
I only tested in on Linux (`test_h5filter` pass).
If you are interested by this approach, please let me know.

I can test it on Windows as well, I can't however test it on macOS.

related to issue #76

### CODE REVIEW

**Comment by nritsche** [comment]
Thanks so much for this contribution @t20100. We should change this in the documentation, too and remove the h5py source-build from the requirements.

**Comment by t20100** [comment]
Hi,
If you are interested I can have a second look at this PR.

You should no longer need to build h5py` and share the same libhdf5 with the filter, but you still need the HDF5 headers to build the filter (unless you bundle them here or provide wheels).

BTW, we bundle the bitshuffle hdf5 filter along with others in [`hdfplugin`](https://github.com/silx-kit/hdf5plugin).

**Comment by nritsche** [comment]
> Hi,
> If you are interested I can have a second look at this PR.
> 
> You should no longer need to build h5py` and share the same libhdf5 with the filter, but you still need the HDF5 headers to build the filter (unless you bundle them here or provide wheels).
> 
> BTW, we bundle the bitshuffle hdf5 filter along with others in [`hdfplugin`](https://github.com/silx-kit/hdf5plugin).

Great! Let's get this PR merged. I think what is mainly missing is
- [ ] change the requirements file
- [ ] update documentation

Once that's done and this PR merged, we can get a working version to pypi.

**Comment by jrs65** [comment]
@james-s-willis maybe you can take a look at this? I think if we merge it *before* the zstd changes it may keep the FRB folks happier as we can maybe binary wheels and save them some of the bitshuffle build complexity (which we've just increased).

**Comment by james-s-willis** [comment]
I think this is ready to be reviewed, @jrs65.

**Review by jrs65 — APPROVED** [review]
@james-s-willis this looks great. Have you experimented with this one by hand on any systems?

**Comment by james-s-willis** [comment]
@jrs65 I tried this on our local machine `magenta`. I removed `bitshuffle` and `h5py` and reinstalled with `pip3 install h5py`. The unit tests still pass:
```
[willis@magenta tests]$ python3 -m pytest
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.7.9, pytest-5.3.0, py-1.8.0, pluggy-0.13.0
rootdir: /home/willis/dynamic-hdf5-loading
plugins: timeout-1.4.2, forked-1.1.3, xdist-1.30.0, localserver-0.5.0, cpp-1.1.0, pyfakefs-4.5.0
collected 61 items                                                                                                                                                                                                

test_ext.py ........................................................                                                                                                                                        [ 91%]
test_h5filter.py ...                                                                                                                                                                                        [ 96%]
test_h5plugin.py .                                                                                                                                                                                          [ 98%]
test_regression.py .                                                                                                                                                                                        [100%]

=============================================================================================== 61 passed in 1.89s ================================================================================================

```
Should I merge this now?

**Comment by jrs65** [comment]
> Should I merge this now?

Go for it!

**Pull request merged**
