### PR TITLE
Improve trans and untrans with AVX512

### PR DESCRIPTION
**Pull request by HackToday**
Signed-off-by: Wu, Kaiqiang <kaiqiang.wu@intel.com>
Co-authored-by: vesslanjin <jun.i.jin@intel.com>

### CODE REVIEW

**Comment by HackToday** [comment]
With performance test against AVX2 and AVX512,  I test against 4 byte elem, elem size varies from 8-120(incr step 8),
Performance speedup ratio can be 0.94x~1.5x,  
even in some cases not better than AVX2, it could keep nearly same performance.  In summary, AVX512 could be a benefit for some modern platforms.

**Comment by HackToday** [comment]
@jrs65 and @kiyo-masui  Could you help check if it is OK for such feature enablement for this repo?

**Comment by HackToday** [comment]
@jrs65 and @kiyo-masui  please help check if missed

**Comment by jrs65** [comment]
Hi @HackToday. Sorry for the belated response, it's been a busy end to the semester for myself (and Kiyo too I imagine).

Thanks for putting this together, it's definitely appreciated. Your code looks good to me, but I need to look around for an AVX512 machine for me to run the tests on as I think Github actions doesn't use any AVX512 supporting hosts.

Also, I'm intrigued if you have any benchmarks of this. How much does AVX512 support speed things up?

**Comment by HackToday** [comment]
hi @jrs65 Thanks for your reply.

For AVX512 available system, I tested against with PR changes,  to count following 

```
bshuf_trans_byte_elem_SSE
bshuf_trans_bit_byte_XXX (can be SSE, AVX, AVX512)
```

The tests show that total element size varies from 8-120(8, 16, 24, 32 etc. step 8, as  Fig1 x label), 4 byte element.
Performance speedup ratio can be 0.94x~1.5x,  Please check Fig1.

image
      **Fig 1**

even in some cases not better than AVX2, it could keep nearly same performance.

Please let me know if need more info.

**Comment by HackToday** [comment]
@jrs65 and @kiyo-masui  in case anything missed. BTW, the workflows CI seems need approval to run.

**Comment by jrs65** [comment]
Hi @HackToday

Thanks for all your efforts here, and apologies for the slow responses. I've got the code built and running on one of my own machines (the cluster we use has some AVX512 nodes), and on the machine that you gave me access to elsewhere. Everything seems to run fine, and with a nice speed boost.

I'm going to merge your code in now. I'll wait a few weeks to cut a release (mostly as I'm going on vacation) but also so I can see about merging in a few other outstanding PRs.

**Comment by HackToday** [comment]
Thanks @jrs65 for your time and help for the verification.

**Pull request merged**
