### PR TITLE
Install h5py without wheel test

### PR DESCRIPTION
**Pull request by james-s-willis**

### CODE REVIEW

**Comment by t20100** [comment]
I tried to reproduce locally following similar steps as in CI:
- on Ubuntu 20.04 (libhdf5 1.10.4, python 3.8) with h5py 3.1.0: Segmentation fault during import
- on Debian10 (libhdf5 1.10.4, python 3.7) with h5py 3.1.0: worked fine.

We never got such issue reported to `hdf5plugin` and it worked in both cases.

**Comment by t20100** [comment]
It looks to be related to calling `init_filter` from cython code.

I made it work by commenting the calls to `init_filter` and `register_h5_filter` in `h5.pyx` and running:
```python
from bitshuffle import h5
import h5py, ctypes

lib = ctypes.CDLL(h5.__file__)
lib.init_filter.argtypes = [ctypes.c_char_p]
lib.init_filter.restype = ctypes.c_int
lib.init_filter(bytes(h5py.h5z.__file__, encoding='utf-8'))

h5.register_h5_filter()
```

**Comment by james-s-willis** [comment]
Thanks for looking into this. I found that H5E_CANTREGISTER_g, H5E_CALLBACK_g, H5E_PLINE_g, H5E_ERR_CLS_g symbols are not included in `h5py.h5d` when `h5py` is installed with `--no-binary=h5py`. If you use `h5py.h5z` (like in your fix) to initialise the filter it works fine.

**Comment by t20100** [comment]
Good! I actually use `h5z` in `hdf5plugin`, but I didn't expected that would make a difference to use another... maybe it depends on the way h5py links to libhdf5.

**Pull request closed without merging**
