### PR TITLE
update lz4 to 1.9.3 and replace deprecated lz4 functions

### PR DESCRIPTION
**Pull request by weninc**

### CODE REVIEW

**Comment by jonwright** [comment]
(Please excuse my uninvited comments - I am someone who uses this code)

- Allowing people to select an LZ4 version at compile time would let them link to Intel's IPP patched versions more easily. This is a little faster for certain use cases on intel processors. We would need to be able to define the include + link arguments for setup.py to use another version rather than the one that is bundled.

- There is a comment in the LZ4 sources saying not to use the fast variants any more, get rid of this https://github.com/kiyo-masui/bitshuffle/blob/6899f5db159469e92e7b3c776d2087345e4d5b77/src/bitshuffle.c#L23 The recommendation comes from your lz4.h:
```
 Obsolete LZ4_decompress_fast variants (since v1.9.0) :
 *  These functions used to be faster than LZ4_decompress_safe(),
 *  but this is no longer the case. They are now slower.
 ```

Hopefully these comments are useful.

**Comment by weninc** [comment]
* Yes I agree being able to select the LZ4 version on compile time is very useful. Maybe that's best as a separate PR?

* Good catch. I replaced the deprecated lz4 functions LZ4_decompress_fast and LZ4_compress.

**Comment by james-s-willis** [comment]
Hey @weninc, thanks for these changes! Are you able to update your fork? Then I can merge this PR. Thanks.

**Comment by weninc** [comment]
Great thanks. I just updated my fork

**Pull request merged**
